# Generated by Django 5.2.2 on 2025-06-04 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_subject_subjectattendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectattendance',
            name='notes',
            field=models.TextField(blank=True, help_text='Any additional notes about this attendance record', null=True),
        ),
        migrations.CreateModel(
            name='ClassPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Period 1', 'Morning Class'", max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days_of_week', models.CharField(help_text="e.g. 'MWF' for Monday, Wednesday, Friday", max_length=20)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.subject')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='subjectattendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subjectattendance',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.classperiod'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectattendance',
            unique_together={('user', 'subject', 'date', 'period')},
        ),
    ]
